name: ShadowStream_Ultimate_Builder
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Python Hazırla
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Gereksinimleri Yükle
      run: pip install pyinstaller requests
    - name: YouTube Motorunu Çek (yt-dlp)
      run: |
        mkdir Tools
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe -o Tools/yt-dlp.exe
    - name: EXE Oluştur (Her Şey Dahil)
      run: |
        pyinstaller --onefile --noconsole --add-data "Tools/yt-dlp.exe;Tools" shadow.py
    - name: EXE Teslim Et
      uses: actions/upload-artifact@v4
      with:
        name: ShadowStream_Final_Pack
        path: dist/shadow.exe
