name: ShadowStream_EXE_Builder
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Python Kur
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Kütüphaneleri Yükle
      run: pip install pyinstaller requests
    - name: EXE Oluştur
      run: pyinstaller --onefile --noconsole --icon=NONE shadow.py
    - name: Dosyayı Teslim Et
      uses: actions/upload-artifact@v4
      with:
        name: ShadowStream_Portable_EXE
        path: dist/shadow.exe
